-- GENERATED by scripts/gen_guards.py -- the triggers below ARE the owner-state protections.
-- They rely on the application-defined function current_actor(), which each connection
-- registers for its role. A connection without it (e.g. the sqlite3 shell) cannot write
-- any guarded table: SQLite raises 'no such function' and the write fails closed.

-- Seed the lifecycle table, then freeze it.
INSERT INTO state_transition VALUES ('<none>','DISCOVERED',',agent,system,owner,',NULL);
INSERT INTO state_transition VALUES ('DISCOVERED','VERIFYING',',agent,system,',NULL);
INSERT INTO state_transition VALUES ('VERIFYING','OWNER_REVIEW',',agent,system,',NULL);
INSERT INTO state_transition VALUES ('VERIFYING','WATCHLIST',',agent,system,',NULL);
INSERT INTO state_transition VALUES ('VERIFYING','DISQUALIFIED',',agent,system,',NULL);
INSERT INTO state_transition VALUES ('WATCHLIST','VERIFYING',',agent,system,',NULL);
INSERT INTO state_transition VALUES ('WATCHLIST','DISQUALIFIED',',agent,system,',NULL);
INSERT INTO state_transition VALUES ('OWNER_REVIEW','APPROVED',',owner,','approve');
INSERT INTO state_transition VALUES ('OWNER_REVIEW','DECLINED',',owner,','decline');
INSERT INTO state_transition VALUES ('OWNER_REVIEW','WATCHLIST',',owner,','watch');
INSERT INTO state_transition VALUES ('OWNER_REVIEW','DISQUALIFIED',',agent,system,',NULL);
INSERT INTO state_transition VALUES ('APPROVED','PREPARING',',agent,system,',NULL);
INSERT INTO state_transition VALUES ('APPROVED','DISQUALIFIED',',agent,system,',NULL);
INSERT INTO state_transition VALUES ('APPROVED','WITHDRAWN',',owner,','withdraw');
INSERT INTO state_transition VALUES ('PREPARING','READY_FOR_REVIEW',',agent,system,',NULL);
INSERT INTO state_transition VALUES ('PREPARING','DISQUALIFIED',',agent,system,',NULL);
INSERT INTO state_transition VALUES ('PREPARING','WITHDRAWN',',owner,','withdraw');
INSERT INTO state_transition VALUES ('READY_FOR_REVIEW','PREPARING',',owner,','request_changes');
INSERT INTO state_transition VALUES ('READY_FOR_REVIEW','SUBMITTED',',owner,','mark_submitted');
INSERT INTO state_transition VALUES ('READY_FOR_REVIEW','WITHDRAWN',',owner,','withdraw');
INSERT INTO state_transition VALUES ('READY_FOR_REVIEW','DISQUALIFIED',',agent,system,',NULL);
INSERT INTO state_transition VALUES ('SUBMITTED','AWAITING_DECISION',',agent,system,owner,',NULL);
INSERT INTO state_transition VALUES ('AWAITING_DECISION','AWARDED',',owner,','mark_awarded');
INSERT INTO state_transition VALUES ('AWAITING_DECISION','NOT_AWARDED',',owner,','mark_not_awarded');
INSERT INTO state_transition VALUES ('AWAITING_DECISION','WITHDRAWN',',owner,','withdraw');
INSERT INTO state_transition VALUES ('DECLINED','VERIFYING',',owner,','reopen');
INSERT INTO state_transition VALUES ('DISQUALIFIED','VERIFYING',',owner,','reopen');

CREATE TRIGGER state_transition_frozen_insert BEFORE INSERT ON state_transition
BEGIN
  SELECT RAISE(ABORT, 'state_transition is frozen') WHERE 1;
END;
CREATE TRIGGER state_transition_frozen_update BEFORE UPDATE ON state_transition
BEGIN
  SELECT RAISE(ABORT, 'state_transition is frozen') WHERE 1;
END;
CREATE TRIGGER state_transition_frozen_delete BEFORE DELETE ON state_transition
BEGIN
  SELECT RAISE(ABORT, 'state_transition is frozen') WHERE 1;
END;
CREATE TRIGGER status_event_append_only_update BEFORE UPDATE ON status_event
BEGIN
  SELECT RAISE(ABORT, 'status_event is append-only') WHERE 1;
END;
CREATE TRIGGER status_event_append_only_delete BEFORE DELETE ON status_event
BEGIN
  SELECT RAISE(ABORT, 'status_event is append-only') WHERE 1;
END;
CREATE TRIGGER decision_append_only_update BEFORE UPDATE ON decision
BEGIN
  SELECT RAISE(ABORT, 'decision is append-only') WHERE 1;
END;
CREATE TRIGGER decision_append_only_delete BEFORE DELETE ON decision
BEGIN
  SELECT RAISE(ABORT, 'decision is append-only') WHERE 1;
END;
CREATE TRIGGER evidence_append_only_update BEFORE UPDATE ON evidence
BEGIN
  SELECT RAISE(ABORT, 'evidence is append-only') WHERE 1;
END;
CREATE TRIGGER evidence_append_only_delete BEFORE DELETE ON evidence
BEGIN
  SELECT RAISE(ABORT, 'evidence is append-only') WHERE 1;
END;
CREATE TRIGGER evidence_supersession_append_only_update BEFORE UPDATE ON evidence_supersession
BEGIN
  SELECT RAISE(ABORT, 'evidence_supersession is append-only') WHERE 1;
END;
CREATE TRIGGER evidence_supersession_append_only_delete BEFORE DELETE ON evidence_supersession
BEGIN
  SELECT RAISE(ABORT, 'evidence_supersession is append-only') WHERE 1;
END;
CREATE TRIGGER assessment_append_only_update BEFORE UPDATE ON assessment
BEGIN
  SELECT RAISE(ABORT, 'assessment is append-only') WHERE 1;
END;
CREATE TRIGGER assessment_append_only_delete BEFORE DELETE ON assessment
BEGIN
  SELECT RAISE(ABORT, 'assessment is append-only') WHERE 1;
END;
CREATE TRIGGER assessment_evidence_append_only_update BEFORE UPDATE ON assessment_evidence
BEGIN
  SELECT RAISE(ABORT, 'assessment_evidence is append-only') WHERE 1;
END;
CREATE TRIGGER assessment_evidence_append_only_delete BEFORE DELETE ON assessment_evidence
BEGIN
  SELECT RAISE(ABORT, 'assessment_evidence is append-only') WHERE 1;
END;
CREATE TRIGGER source_snapshot_append_only_update BEFORE UPDATE ON source_snapshot
BEGIN
  SELECT RAISE(ABORT, 'source_snapshot is append-only') WHERE 1;
END;
CREATE TRIGGER source_snapshot_append_only_delete BEFORE DELETE ON source_snapshot
BEGIN
  SELECT RAISE(ABORT, 'source_snapshot is append-only') WHERE 1;
END;
CREATE TRIGGER audit_incident_append_only_update BEFORE UPDATE ON audit_incident
BEGIN
  SELECT RAISE(ABORT, 'audit_incident is append-only') WHERE 1;
END;
CREATE TRIGGER audit_incident_append_only_delete BEFORE DELETE ON audit_incident
BEGIN
  SELECT RAISE(ABORT, 'audit_incident is append-only') WHERE 1;
END;
CREATE TRIGGER llm_call_log_append_only_update BEFORE UPDATE ON llm_call_log
BEGIN
  SELECT RAISE(ABORT, 'llm_call_log is append-only') WHERE 1;
END;
CREATE TRIGGER llm_call_log_append_only_delete BEFORE DELETE ON llm_call_log
BEGIN
  SELECT RAISE(ABORT, 'llm_call_log is append-only') WHERE 1;
END;
CREATE TRIGGER egress_log_append_only_update BEFORE UPDATE ON egress_log
BEGIN
  SELECT RAISE(ABORT, 'egress_log is append-only') WHERE 1;
END;
CREATE TRIGGER egress_log_append_only_delete BEFORE DELETE ON egress_log
BEGIN
  SELECT RAISE(ABORT, 'egress_log is append-only') WHERE 1;
END;
CREATE TRIGGER discovery_hit_append_only_update BEFORE UPDATE ON discovery_hit
BEGIN
  SELECT RAISE(ABORT, 'discovery_hit is append-only') WHERE 1;
END;
CREATE TRIGGER discovery_hit_append_only_delete BEFORE DELETE ON discovery_hit
BEGIN
  SELECT RAISE(ABORT, 'discovery_hit is append-only') WHERE 1;
END;
CREATE TRIGGER owner_profile_owner_only_insert BEFORE INSERT ON owner_profile
BEGIN
  SELECT RAISE(ABORT, 'owner_profile is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER owner_profile_owner_only_update BEFORE UPDATE ON owner_profile
BEGIN
  SELECT RAISE(ABORT, 'owner_profile is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER owner_profile_owner_only_delete BEFORE DELETE ON owner_profile
BEGIN
  SELECT RAISE(ABORT, 'owner_profile is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER business_profile_owner_only_insert BEFORE INSERT ON business_profile
BEGIN
  SELECT RAISE(ABORT, 'business_profile is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER business_profile_owner_only_update BEFORE UPDATE ON business_profile
BEGIN
  SELECT RAISE(ABORT, 'business_profile is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER business_profile_owner_only_delete BEFORE DELETE ON business_profile
BEGIN
  SELECT RAISE(ABORT, 'business_profile is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER project_owner_only_insert BEFORE INSERT ON project
BEGIN
  SELECT RAISE(ABORT, 'project is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER project_owner_only_update BEFORE UPDATE ON project
BEGIN
  SELECT RAISE(ABORT, 'project is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER project_owner_only_delete BEFORE DELETE ON project
BEGIN
  SELECT RAISE(ABORT, 'project is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER project_fact_owner_only_insert BEFORE INSERT ON project_fact
BEGIN
  SELECT RAISE(ABORT, 'project_fact is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER project_fact_owner_only_update BEFORE UPDATE ON project_fact
BEGIN
  SELECT RAISE(ABORT, 'project_fact is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER project_fact_owner_only_delete BEFORE DELETE ON project_fact
BEGIN
  SELECT RAISE(ABORT, 'project_fact is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER restricted_stub_owner_only_insert BEFORE INSERT ON restricted_stub
BEGIN
  SELECT RAISE(ABORT, 'restricted_stub is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER restricted_stub_owner_only_update BEFORE UPDATE ON restricted_stub
BEGIN
  SELECT RAISE(ABORT, 'restricted_stub is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER restricted_stub_owner_only_delete BEFORE DELETE ON restricted_stub
BEGIN
  SELECT RAISE(ABORT, 'restricted_stub is writable by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER decision_owner_only_insert BEFORE INSERT ON decision
BEGIN
  SELECT RAISE(ABORT, 'decisions can only be recorded by the owner') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER opportunity_insert_state BEFORE INSERT ON opportunity
BEGIN
  SELECT RAISE(ABORT, 'new opportunities start DISCOVERED') WHERE NEW.state <> 'DISCOVERED';
END;
CREATE TRIGGER opportunity_no_delete BEFORE DELETE ON opportunity
BEGIN
  SELECT RAISE(ABORT, 'opportunities are never deleted') WHERE 1;
END;
CREATE TRIGGER opportunity_immutable_cols BEFORE UPDATE OF id, canonical_key, first_discovered ON opportunity
BEGIN
  SELECT RAISE(ABORT, 'immutable column') WHERE NEW.id <> OLD.id OR NEW.canonical_key <> OLD.canonical_key OR NEW.first_discovered <> OLD.first_discovered;
END;
CREATE TRIGGER opportunity_state_follows_event BEFORE UPDATE OF state ON opportunity
BEGIN
  SELECT RAISE(ABORT, 'state may only change through status_event')
  WHERE NEW.state <> OLD.state AND NOT EXISTS (
    SELECT 1 FROM status_event e
    WHERE e.opportunity_id = OLD.id AND e.from_state = OLD.state AND e.to_state = NEW.state
      AND e.rowid = (SELECT max(rowid) FROM status_event WHERE opportunity_id = OLD.id));
END;
CREATE TRIGGER opportunity_creation_event AFTER INSERT ON opportunity
BEGIN
  INSERT INTO status_event (id, opportunity_id, at, from_state, to_state, actor, reason)
  VALUES ('ev-' || NEW.id, NEW.id, NEW.first_discovered, NULL, 'DISCOVERED', current_actor(), 'discovered');
END;
CREATE TRIGGER status_event_guard BEFORE INSERT ON status_event
BEGIN
  SELECT RAISE(ABORT, 'actor does not match connection role')
    WHERE NEW.actor IS NOT current_actor();
  SELECT RAISE(ABORT, 'illegal transition or actor not permitted')
    WHERE NOT EXISTS (
      SELECT 1 FROM state_transition t
      WHERE t.from_state = COALESCE(NEW.from_state, '<none>') AND t.to_state = NEW.to_state
        AND instr(t.actors, ',' || NEW.actor || ',') > 0);
  SELECT RAISE(ABORT, 'duplicate creation event')
    WHERE NEW.from_state IS NULL AND EXISTS (SELECT 1 FROM status_event WHERE opportunity_id = NEW.opportunity_id);
  SELECT RAISE(ABORT, 'stale from_state')
    WHERE NEW.from_state IS NOT NULL
      AND NEW.from_state IS NOT (SELECT state FROM opportunity WHERE id = NEW.opportunity_id);
  SELECT RAISE(ABORT, 'owner decision required for this transition')
    WHERE (SELECT requires_decision FROM state_transition t
           WHERE t.from_state = COALESCE(NEW.from_state, '<none>') AND t.to_state = NEW.to_state) IS NOT NULL
      AND NOT EXISTS (
        SELECT 1 FROM decision d, state_transition t
        WHERE d.id = NEW.decision_id AND d.opportunity_id = NEW.opportunity_id AND d.actor = 'owner'
          AND t.from_state = COALESCE(NEW.from_state, '<none>') AND t.to_state = NEW.to_state
          AND d.decision = t.requires_decision);
END;
CREATE TRIGGER status_event_apply AFTER INSERT ON status_event
BEGIN
  UPDATE opportunity SET state = NEW.to_state WHERE id = NEW.opportunity_id;
END;
CREATE TRIGGER evidence_snapshot_match BEFORE INSERT ON evidence
BEGIN
  SELECT RAISE(ABORT, 'evidence and snapshot belong to different opportunities')
  WHERE NOT EXISTS (SELECT 1 FROM source_snapshot s WHERE s.id = NEW.snapshot_id AND s.opportunity_id = NEW.opportunity_id);
END;
CREATE TRIGGER evidence_supersession_match BEFORE INSERT ON evidence_supersession
BEGIN
  SELECT RAISE(ABORT, 'superseding evidence must be same opportunity and field')
  WHERE NOT EXISTS (
    SELECT 1 FROM evidence a, evidence b
    WHERE a.id = NEW.evidence_id AND b.id = NEW.superseded_by
      AND a.opportunity_id = b.opportunity_id AND a.field = b.field AND a.id <> b.id);
END;
CREATE TRIGGER preference_agent_suggest_only BEFORE INSERT ON preference
BEGIN
  SELECT RAISE(ABORT, 'only the owner can create active or non-suggested preferences')
  WHERE current_actor() IS NOT 'owner' AND (NEW.origin <> 'suggested' OR NEW.active <> 0);
END;
CREATE TRIGGER preference_owner_only_update BEFORE UPDATE ON preference
BEGIN
  SELECT RAISE(ABORT, 'preferences are changed by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER preference_owner_only_delete BEFORE DELETE ON preference
BEGIN
  SELECT RAISE(ABORT, 'preferences are changed by the owner only') WHERE current_actor() IS NOT 'owner';
END;
CREATE TRIGGER prerequisite_done_owner_only BEFORE UPDATE OF status ON prerequisite
BEGIN
  SELECT RAISE(ABORT, 'only the owner can mark a prerequisite done or reopen it')
  WHERE current_actor() IS NOT 'owner' AND (NEW.status = 'done' OR OLD.status = 'done');
END;
CREATE TRIGGER prerequisite_insert_not_done BEFORE INSERT ON prerequisite
BEGIN
  SELECT RAISE(ABORT, 'new prerequisites cannot start done unless owner')
  WHERE current_actor() IS NOT 'owner' AND NEW.status = 'done';
END;
CREATE TRIGGER prerequisite_no_delete BEFORE DELETE ON prerequisite
BEGIN
  SELECT RAISE(ABORT, 'prerequisites are not deleted') WHERE current_actor() IS NOT 'owner';
END;
