T = [
 ('<none>','DISCOVERED','agent,system,owner',None),
 ('DISCOVERED','VERIFYING','agent,system',None),
 ('VERIFYING','OWNER_REVIEW','agent,system',None),
 ('VERIFYING','WATCHLIST','agent,system',None),
 ('VERIFYING','DISQUALIFIED','agent,system',None),
 ('WATCHLIST','VERIFYING','agent,system',None),
 ('WATCHLIST','DISQUALIFIED','agent,system',None),
 ('OWNER_REVIEW','APPROVED','owner','approve'),
 ('OWNER_REVIEW','DECLINED','owner','decline'),
 ('OWNER_REVIEW','WATCHLIST','owner','watch'),
 ('OWNER_REVIEW','DISQUALIFIED','agent,system',None),
 ('APPROVED','PREPARING','agent,system',None),
 ('APPROVED','DISQUALIFIED','agent,system',None),
 ('APPROVED','WITHDRAWN','owner','withdraw'),
 ('PREPARING','READY_FOR_REVIEW','agent,system',None),
 ('PREPARING','DISQUALIFIED','agent,system',None),
 ('PREPARING','WITHDRAWN','owner','withdraw'),
 ('READY_FOR_REVIEW','PREPARING','owner','request_changes'),
 ('READY_FOR_REVIEW','SUBMITTED','owner','mark_submitted'),
 ('READY_FOR_REVIEW','WITHDRAWN','owner','withdraw'),
 ('READY_FOR_REVIEW','DISQUALIFIED','agent,system',None),
 ('SUBMITTED','AWAITING_DECISION','agent,system,owner',None),
 ('AWAITING_DECISION','AWARDED','owner','mark_awarded'),
 ('AWAITING_DECISION','NOT_AWARDED','owner','mark_not_awarded'),
 ('AWAITING_DECISION','WITHDRAWN','owner','withdraw'),
 ('DECLINED','VERIFYING','owner','reopen'),
 ('DISQUALIFIED','VERIFYING','owner','reopen'),
]
out = []
w = out.append
w("-- GENERATED by scripts/gen_guards.py -- the triggers below ARE the owner-state protections.")
w("-- They rely on the application-defined function current_actor(), which each connection")
w("-- registers for its role. A connection without it (e.g. the sqlite3 shell) cannot write")
w("-- any guarded table: SQLite raises 'no such function' and the write fails closed.")
w("")
w("-- Seed the lifecycle table, then freeze it.")
for f, t, a, d in T:
    dec = "NULL" if d is None else f"'{d}'"
    w(f"INSERT INTO state_transition VALUES ('{f}','{t}',',{a},',{dec});")
w("")
def abort(name, when, event, table, cond, msg):
    w(f"CREATE TRIGGER {name} BEFORE {event} ON {table}\nBEGIN\n  SELECT RAISE(ABORT, '{msg}') WHERE {cond};\nEND;")

# immutable lifecycle table
for ev in ("INSERT","UPDATE","DELETE"):
    abort(f"state_transition_frozen_{ev.lower()}", "", ev, "state_transition", "1", "state_transition is frozen")

# append-only tables
APPEND_ONLY = ["status_event","decision","evidence","evidence_supersession","assessment",
               "assessment_evidence","source_snapshot","audit_incident","llm_call_log",
               "egress_log","discovery_hit"]
for tb in APPEND_ONLY:
    for ev in ("UPDATE","DELETE"):
        abort(f"{tb}_append_only_{ev.lower()}", "", ev, tb, "1", f"{tb} is append-only")

# owner-only tables
OWNER_ONLY = ["owner_profile","business_profile","project","project_fact","restricted_stub"]
for tb in OWNER_ONLY:
    for ev in ("INSERT","UPDATE","DELETE"):
        abort(f"{tb}_owner_only_{ev.lower()}", "", ev, tb, "current_actor() IS NOT 'owner'", f"{tb} is writable by the owner only")
abort("decision_owner_only_insert", "", "INSERT", "decision", "current_actor() IS NOT 'owner'", "decisions can only be recorded by the owner")

# opportunity guards
abort("opportunity_insert_state", "", "INSERT", "opportunity", "NEW.state <> 'DISCOVERED'", "new opportunities start DISCOVERED")
abort("opportunity_no_delete", "", "DELETE", "opportunity", "1", "opportunities are never deleted")
w("""CREATE TRIGGER opportunity_immutable_cols BEFORE UPDATE OF id, canonical_key, first_discovered ON opportunity
BEGIN
  SELECT RAISE(ABORT, 'immutable column') WHERE NEW.id <> OLD.id OR NEW.canonical_key <> OLD.canonical_key OR NEW.first_discovered <> OLD.first_discovered;
END;""")
w("""CREATE TRIGGER opportunity_state_follows_event BEFORE UPDATE OF state ON opportunity
BEGIN
  SELECT RAISE(ABORT, 'state may only change through status_event')
  WHERE NEW.state <> OLD.state AND NOT EXISTS (
    SELECT 1 FROM status_event e
    WHERE e.opportunity_id = OLD.id AND e.from_state = OLD.state AND e.to_state = NEW.state
      AND e.rowid = (SELECT max(rowid) FROM status_event WHERE opportunity_id = OLD.id));
END;""")
w("""CREATE TRIGGER opportunity_creation_event AFTER INSERT ON opportunity
BEGIN
  INSERT INTO status_event (id, opportunity_id, at, from_state, to_state, actor, reason)
  VALUES ('ev-' || NEW.id, NEW.id, NEW.first_discovered, NULL, 'DISCOVERED', current_actor(), 'discovered');
END;""")

# status_event guard
w("""CREATE TRIGGER status_event_guard BEFORE INSERT ON status_event
BEGIN
  SELECT RAISE(ABORT, 'actor does not match connection role')
    WHERE NEW.actor IS NOT current_actor();
  SELECT RAISE(ABORT, 'illegal transition or actor not permitted')
    WHERE NOT EXISTS (
      SELECT 1 FROM state_transition t
      WHERE t.from_state = COALESCE(NEW.from_state, '<none>') AND t.to_state = NEW.to_state
        AND instr(t.actors, ',' || NEW.actor || ',') > 0);
  SELECT RAISE(ABORT, 'duplicate creation event')
    WHERE NEW.from_state IS NULL AND EXISTS (SELECT 1 FROM status_event WHERE opportunity_id = NEW.opportunity_id);
  SELECT RAISE(ABORT, 'stale from_state')
    WHERE NEW.from_state IS NOT NULL
      AND NEW.from_state IS NOT (SELECT state FROM opportunity WHERE id = NEW.opportunity_id);
  SELECT RAISE(ABORT, 'owner decision required for this transition')
    WHERE (SELECT requires_decision FROM state_transition t
           WHERE t.from_state = COALESCE(NEW.from_state, '<none>') AND t.to_state = NEW.to_state) IS NOT NULL
      AND NOT EXISTS (
        SELECT 1 FROM decision d, state_transition t
        WHERE d.id = NEW.decision_id AND d.opportunity_id = NEW.opportunity_id AND d.actor = 'owner'
          AND t.from_state = COALESCE(NEW.from_state, '<none>') AND t.to_state = NEW.to_state
          AND d.decision = t.requires_decision);
END;""")
w("""CREATE TRIGGER status_event_apply AFTER INSERT ON status_event
BEGIN
  UPDATE opportunity SET state = NEW.to_state WHERE id = NEW.opportunity_id;
END;""")

# evidence consistency
w("""CREATE TRIGGER evidence_snapshot_match BEFORE INSERT ON evidence
BEGIN
  SELECT RAISE(ABORT, 'evidence and snapshot belong to different opportunities')
  WHERE NOT EXISTS (SELECT 1 FROM source_snapshot s WHERE s.id = NEW.snapshot_id AND s.opportunity_id = NEW.opportunity_id);
END;""")
w("""CREATE TRIGGER evidence_supersession_match BEFORE INSERT ON evidence_supersession
BEGIN
  SELECT RAISE(ABORT, 'superseding evidence must be same opportunity and field')
  WHERE NOT EXISTS (
    SELECT 1 FROM evidence a, evidence b
    WHERE a.id = NEW.evidence_id AND b.id = NEW.superseded_by
      AND a.opportunity_id = b.opportunity_id AND a.field = b.field AND a.id <> b.id);
END;""")

# preferences: agents may only *suggest*
w("""CREATE TRIGGER preference_agent_suggest_only BEFORE INSERT ON preference
BEGIN
  SELECT RAISE(ABORT, 'only the owner can create active or non-suggested preferences')
  WHERE current_actor() IS NOT 'owner' AND (NEW.origin <> 'suggested' OR NEW.active <> 0);
END;""")
for ev in ("UPDATE","DELETE"):
    abort(f"preference_owner_only_{ev.lower()}", "", ev, "preference", "current_actor() IS NOT 'owner'", "preferences are changed by the owner only")

# prerequisites: only the owner can mark done / un-done
w("""CREATE TRIGGER prerequisite_done_owner_only BEFORE UPDATE OF status ON prerequisite
BEGIN
  SELECT RAISE(ABORT, 'only the owner can mark a prerequisite done or reopen it')
  WHERE current_actor() IS NOT 'owner' AND (NEW.status = 'done' OR OLD.status = 'done');
END;""")
w("""CREATE TRIGGER prerequisite_insert_not_done BEFORE INSERT ON prerequisite
BEGIN
  SELECT RAISE(ABORT, 'new prerequisites cannot start done unless owner')
  WHERE current_actor() IS NOT 'owner' AND NEW.status = 'done';
END;""")
w("""CREATE TRIGGER prerequisite_no_delete BEFORE DELETE ON prerequisite
BEGIN
  SELECT RAISE(ABORT, 'prerequisites are not deleted') WHERE current_actor() IS NOT 'owner';
END;""")
print("\n".join(out))
